### ISSUE TITLE
SSL no working properly

### ISSUE THREAD

**Issue by nionis** [hoprnet/playground#21]
Loading up https://playground-alpha.hoprtech.net/api/clusters shows that the certificate is not valid.
![image](https://github.com/hoprnet/playground/assets/1877679/0917291f-b837-41a6-b417-939d73081440)

**Comment by nionis** [comment]
I can no longer replicate the issue live, also got this email 
<img width="656" alt="image" src="https://github.com/hoprnet/playground/assets/1877679/44549c92-b8a5-41ac-8586-f3f29a816b3f">

**Comment by mjadach-iv** [comment]
After internal discussion, moved the task to devops repo
https://github.com/hoprnet/hopr-devops/issues/155
